[package]
name = "natvis4qt"
version = "0.8.0"
edition = "2021"

[[bin]]
name = "natvis4qt"
path = "src/main.rs"

[dependencies]
dirs = "6.0"
cliclack = "0.3.7"
ctrlc = "3.5"
console = "0.16"
clap = { version = "4.5", features = ["derive"] }
preferences = "2.0"
