[package]
name = "natvis4qt"
version = "0.7.0"
edition = "2021"

[[bin]]
name = "natvis4qt"
path = "src/main.rs"

[dependencies]
dirs = "6.0"
cliclack = "0.3.5"
ctrlc = "3.1"
console = "0.16.1"
clap = { version = "4.5", features = ["derive"] }
preferences = "2.0"
